### ISSUE TITLE
my test 0.13.0

### ISSUE THREAD

**Issue by AS400JPLPC** [Calder-Ty/ztui#17]
[Ztui.tar.gz](https://github.com/user-attachments/files/16237800/Ztui.tar.gz)

**Comment by Calder-Ty** [comment]
Thanks for looking into this, Could you link to something that isn't a ZIP file?

**Comment by AS400JPLPC** [comment]
update Ztui

**Comment by Calder-Ty** [comment]
There's a new release https://github.com/Calder-Ty/ztui/releases/tag/tabby-0.2.0, that is up to date with version 0.13.0 of the compiler. 

I'm not experiencing the issues with è that you mentioned on ziggit. Could you explain more what you are seeing?

**Comment by AS400JPLPC** [comment]
not all characters work ex: éàçèôîï€ëæäßùø... utf8 

the characters that work: azertyuiopqsdfghjklmwxcvbn 0123456789 &~#"'{}()[]-|_\@=+/£$µ*%§!/:.;?, only basic ansi

**Comment by Calder-Ty** [comment]
I Think the issue is resolved, If you could test it out on master.
